### PR TITLE
Soundvolumes

### PR DESCRIPTION
**Pull request by codesalad**
Added sliders to adjust sound effect volume and music volume.
Removed duplicate resource folder/refactored code with Viktor.
Added new sprites for explosion, powerup, bullet, nuke bullet.
<feature

### CODE REVIEW

**Comment by vwigmore** [comment]
I've put the spritemanager into the thememanager and added the spawn coordinates of bullets and explosions to be determined dynamically with getHeight and getWidth

**Comment by codesalad** [comment]
*slow clap*, new theme is still applied to new sprites in the new level. Good job.

**Comment by skulane** [comment]
The pom.xml is missing coberture. This means that we're missing the codecoverage report. Pleas add this back into the pom.xml before this pull request is accepted. Everything else is good.<review

**Comment by MKlaassen** [comment]
Wow, great job.

**Pull request merged**
