### PR TITLE
Added pause by pressing 'P'

### PR DESCRIPTION
**Pull request by Emielvr**
Game will pause if the P button is pressed.

### CODE REVIEW

**Comment by vwigmore** [comment]
Looks good, nicely done

**Comment by skulane** [comment]
Absolutely amazing, the pause works like a charm. It does what it should do. However I do agree with @vwigmore, it would be nice to have a notice that the game is paused if it's possible. But even in this situation I do approve the merge.

**Comment by codesalad** [comment]
It works like expected, nice. 
I'm implementing the paused notification at this moment so a commit will come within 10 minutes.

**Comment by codesalad** [comment]
Alright, added paused notification. 
I had to change the way observers are notified, they'll keep notifying after the game is paused, but the level will only process the tick if the game is not paused.

Feel free to check for errors.

**Comment by skulane** [comment]
Look good, the notice is working and only showing up when needed so good job! I approve this merge conflict.

**Pull request merged**
